language: objective-c
osx_image: xcode8.3
rvm:
- 2.2
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- travis_wait 60 ./Scripts/install.sh
script:
- travis_wait 60 ./Scripts/build.sh
